### ISSUE TITLE
qgis_session_info() error

### ISSUE THREAD

**Issue by luisspuerto** [jannes-m/RQGIS#75] opened 2017-07-10 18:38 UTC
Hi, 

I've manage to install everything I think I needed to install rqgis, but when I execute qgis_session_info() R return me this: 

```
> qgis_session_info()
Checking for homebrew osgeo4mac installation on your system. 

Error in py_run_string_impl(code, local, convert) : 
  NameError: name 'RQGIS' is not defined

Detailed traceback: 
  File "<string>", line 1, in <module>
> set_env()
Checking for homebrew osgeo4mac installation on your system. 

Error in if (no_homebrew[1] == TRUE) { : 
  missing value where TRUE/FALSE needed
> 
```

I think something is not correctly configured, but I think figure out what. 

Can you give me a hand here? 

thanks!

**Comment by luisspuerto** [comment] 2017-07-10 19:30
PS/ I have everything installed through Homebrew.

**Comment by pat-s** [comment] 2017-07-10 19:50
Hi @luisspuerto,

could you please post `brew info qgis2`, `brew info qgis2-ltr` and `devtools::session_info()`?

**Comment by luisspuerto** [comment] 2017-07-10 19:53
```
 ✘ lpuerto@MBP-lpuerto  ~  brew info qgis2
osgeo/osgeo4mac/qgis2: stable 2.18.10, HEAD [keg-only]
Open Source Geographic Information System
https://www.qgis.org
/usr/local/Cellar/qgis2/2.18.10 (754 files, 33.6MB)
  Built from source on 2017-07-08 at 10:56:16 with: --with-grass
From: https://github.com/osgeo/homebrew-osgeo4mac/blob/master/Formula/qgis2.rb
==> Dependencies
Build: cmake ✔, bison ✔, flex ✔
Required: qt-4 ✔, sip-qt4 ✔, pyqt-qt4 ✔, qca-qt4 ✔, qscintilla2-qt4 ✔, qwt-qt4 ✔, qwtpolar-qt4 ✔, qjson-qt4 ✔, gsl ✔, sqlite ✔, expat ✔, proj ✔, spatialindex ✔, fcgi ✔, gdal2 ✔, gdal2-python ✔, grass7 ✔, gettext ✔, pyspatialite ✔
Recommended: postgresql ✔
Optional: gpsbabel-qt4 ✘, grass6 ✘, homebrew/science/r ✔, saga-gis-lts ✔
==> Requirements
Required: unlinkedqgis2 ✔, python ✔
==> Options
--with-api-docs
	Build the API documentation with Doxygen and Graphviz
--with-gdal-1
	Build with GDAL/OGR v1.x instead of v2.x
--with-globe
	Build with Globe plugin, based upon osgEarth
--with-gpsbabel-qt4
	Build with gpsbabel-qt4 support
--with-grass
	Build with GRASS 7 integration plugin and Processing plugin support (or install grass-7x first)
--with-grass6
	Build extra GRASS 6 for Processing plugin
--with-isolation
	Isolate .app's environment to HOMEBREW_PREFIX, to coexist with other QGIS installs
--with-oracle
	Build extra Oracle geospatial database and raster support
--with-orfeo5
	Build extra Orfeo Toolbox for Processing plugin
--with-qspatialite
	Build QSpatialite Qt database driver
--with-r
	Build extra R for Processing plugin
--with-saga-gis
	Build extra Saga GIS for Processing plugin
--with-saga-gis-lts
	Build with saga-gis-lts support
--without-debug
	Disable debug build, which outputs info to system.log or console
--without-postgresql
	Build without current PostgreSQL client
--without-server
	Build without QGIS Server (qgis_mapserv.fcgi)
--HEAD
	Install HEAD version
==> Caveats
Bottles support only Homebrew's Python

QGIS is built as an application bundle. Environment variables for the
Homebrew prefix are embedded in QGIS.app:
  /usr/local/opt/qgis2/QGIS.app

You may also symlink QGIS.app into /Applications or ~/Applications:
  brew linkapps [--local]

To directly run the `QGIS.app/Contents/MacOS/QGIS` binary use the wrapper
script pre-defined with Homebrew prefix environment variables:
  /usr/local/opt/qgis2/bin/qgis2

NOTE: Your current PATH and PYTHONPATH environment variables are honored
      when launching via the wrapper script, while launching QGIS.app
      bundle they are not.

For standalone Python development, set the following environment variable:
  export PYTHONPATH=/usr/local/lib/qt-4/python2.7/site-packages:/usr/local/lib/python2.7/site-packages:$PYTHONPATH

Developer frameworks are installed in:
  /usr/local/opt/qgis2/lib/qgis-dev
  NOTE: not symlinked to HOMEBREW_PREFIX/Frameworks, which affects isolation.
        Use dyld -F option in CPPFLAGS/LDFLAGS when building other software.

If you have built GRASS 6.4.x or 7.0.x support for the Processing plugin set
the following in QGIS:
  Processing->Options: Providers->GRASS commands->GRASS folder to:
     /usr/local/opt/grass6/grass-base
  Processing->Options: Providers->GRASS GIS 7 commands->GRASS 7 folder to:
     /usr/local/opt/grass7/grass-base


This formula is keg-only, which means it was not symlinked into /usr/local,
because to allow for multiple QGIS installs.

If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/qgis2/bin:$PATH"' >> ~/.zshrc

For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/qgis2/lib


If you need Python to find bindings for this keg-only formula, run:
  echo /usr/local/opt/qgis2/lib/python2.7/site-packages >> /usr/local/lib/python2.7/site-packages/qgis2.pth
 lpuerto@MBP-lpuerto  ~  $path
zsh: permission denied: /usr/local/opt/gdal2/bin
 ✘ lpuerto@MBP-lpuerto  ~  $PATH
zsh: no such file or directory: /usr/local/opt/gdal2/bin:/usr/local/sbin:/Users/lpuerto/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin
 ✘ lpuerto@MBP-lpuerto  ~  brew info qgis2
osgeo/osgeo4mac/qgis2: stable 2.18.10, HEAD [keg-only]
Open Source Geographic Information System
https://www.qgis.org
/usr/local/Cellar/qgis2/2.18.10 (754 files, 33.6MB)
  Built from source on 2017-07-08 at 10:56:16 with: --with-grass
From: https://github.com/osgeo/homebrew-osgeo4mac/blob/master/Formula/qgis2.rb
==> Dependencies
Build: cmake ✔, bison ✔, flex ✔
Required: qt-4 ✔, sip-qt4 ✔, pyqt-qt4 ✔, qca-qt4 ✔, qscintilla2-qt4 ✔, qwt-qt4 ✔, qwtpolar-qt4 ✔, qjson-qt4 ✔, gsl ✔, sqlite ✔, expat ✔, proj ✔, spatialindex ✔, fcgi ✔, gdal2 ✔, gdal2-python ✔, grass7 ✔, gettext ✔, pyspatialite ✔
Recommended: postgresql ✔
Optional: gpsbabel-qt4 ✘, grass6 ✘, homebrew/science/r ✔, saga-gis-lts ✔
==> Requirements
Required: unlinkedqgis2 ✔, python ✔
==> Options
--with-api-docs
	Build the API documentation with Doxygen and Graphviz
--with-gdal-1
	Build with GDAL/OGR v1.x instead of v2.x
--with-globe
	Build with Globe plugin, based upon osgEarth
--with-gpsbabel-qt4
	Build with gpsbabel-qt4 support
--with-grass
	Build with GRASS 7 integration plugin and Processing plugin support (or install grass-7x first)
--with-grass6
	Build extra GRASS 6 for Processing plugin
--with-isolation
	Isolate .app's environment to HOMEBREW_PREFIX, to coexist with other QGIS installs
--with-oracle
	Build extra Oracle geospatial database and raster support
--with-orfeo5
	Build extra Orfeo Toolbox for Processing plugin
--with-qspatialite
	Build QSpatialite Qt database driver
--with-r
	Build extra R for Processing plugin
--with-saga-gis
	Build extra Saga GIS for Processing plugin
--with-saga-gis-lts
	Build with saga-gis-lts support
--without-debug
	Disable debug build, which outputs info to system.log or console
--without-postgresql
	Build without current PostgreSQL client
--without-server
	Build without QGIS Server (qgis_mapserv.fcgi)
--HEAD
	Install HEAD version
==> Caveats
Bottles support only Homebrew's Python

QGIS is built as an application bundle. Environment variables for the
Homebrew prefix are embedded in QGIS.app:
  /usr/local/opt/qgis2/QGIS.app

You may also symlink QGIS.app into /Applications or ~/Applications:
  brew linkapps [--local]

To directly run the `QGIS.app/Contents/MacOS/QGIS` binary use the wrapper
script pre-defined with Homebrew prefix environment variables:
  /usr/local/opt/qgis2/bin/qgis2

NOTE: Your current PATH and PYTHONPATH environment variables are honored
      when launching via the wrapper script, while launching QGIS.app
      bundle they are not.

For standalone Python development, set the following environment variable:
  export PYTHONPATH=/usr/local/lib/qt-4/python2.7/site-packages:/usr/local/lib/python2.7/site-packages:$PYTHONPATH

Developer frameworks are installed in:
  /usr/local/opt/qgis2/lib/qgis-dev
  NOTE: not symlinked to HOMEBREW_PREFIX/Frameworks, which affects isolation.
        Use dyld -F option in CPPFLAGS/LDFLAGS when building other software.

If you have built GRASS 6.4.x or 7.0.x support for the Processing plugin set
the following in QGIS:
  Processing->Options: Providers->GRASS commands->GRASS folder to:
     /usr/local/opt/grass6/grass-base
  Processing->Options: Providers->GRASS GIS 7 commands->GRASS 7 folder to:
     /usr/local/opt/grass7/grass-base


This formula is keg-only, which means it was not symlinked into /usr/local,
because to allow for multiple QGIS installs.

If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/qgis2/bin:$PATH"' >> ~/.zshrc

For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/qgis2/lib


If you need Python to find bindings for this keg-only formula, run:
  echo /usr/local/opt/qgis2/lib/python2.7/site-packages >> /usr/local/lib/python2.7/site-packages/qgis2.pth
```

` lpuerto@MBP-lpuerto  ~  brew info qgis2-ltr
osgeo/osgeo4mac/qgis2-ltr: stable 2.14.14, HEAD [keg-only]
Open Source Geographic Information System
https://www.qgis.org
Not installed
From: https://github.com/osgeo/homebrew-osgeo4mac/blob/master/Formula/qgis2-ltr.rb
==> Dependencies
Build: cmake ✔, bison ✔, flex ✔
Required: qt-4 ✔, sip-qt4 ✔, pyqt-qt4 ✔, qca-qt4 ✔, qscintilla2-qt4 ✔, qwt-qt4 ✔, qwtpolar-qt4 ✔, gsl ✔, sqlite ✔, expat ✔, proj ✔, spatialindex ✔, fcgi ✔, gdal2 ✔, gdal2-python ✔, grass7 ✔, gettext ✔, pyspatialite ✔
Recommended: postgresql ✔
Optional: gpsbabel-qt4 ✘, grass6 ✘, homebrew/science/r ✔, saga-gis-lts ✔
==> Requirements
Required: unlinkedqgis2 ✔, python ✔
==> Options
--with-api-docs
	Build the API documentation with Doxygen and Graphviz
--with-gdal-1
	Build with GDAL/OGR v1.x instead of v2.x
--with-globe
	Build with Globe plugin, based upon osgEarth
--with-gpsbabel-qt4
	Build with gpsbabel-qt4 support
--with-grass
	Build with GRASS 7 integration plugin and Processing plugin support (or install grass-7x first)
--with-grass6
	Build extra GRASS 6 for Processing plugin
--with-isolation
	Isolate .app's environment to HOMEBREW_PREFIX, to coexist with other QGIS installs
--with-oracle
	Build extra Oracle geospatial database and raster support
--with-orfeo5
	Build extra Orfeo Toolbox for Processing plugin
--with-qspatialite
	Build QSpatialite Qt database driver
--with-r
	Build extra R for Processing plugin
--with-saga-gis
	Build extra Saga GIS for Processing plugin
--with-saga-gis-lts
	Build with saga-gis-lts support
--without-debug
	Disable debug build, which outputs info to system.log or console
--without-postgresql
	Build without current PostgreSQL client
--without-server
	Build without QGIS Server (qgis_mapserv.fcgi)
--HEAD
	Install HEAD version
==> Caveats
Bottles support only Homebrew's Python

QGIS is built as an application bundle. Environment variables for the
Homebrew prefix are embedded in QGIS.app:
  /usr/local/opt/qgis2-ltr/QGIS.app

You may also symlink QGIS.app into /Applications or ~/Applications:
  brew linkapps [--local]

To directly run the `QGIS.app/Contents/MacOS/QGIS` binary use the wrapper
script pre-defined with Homebrew prefix environment variables:
  /usr/local/opt/qgis2-ltr/bin/qgis2-ltr

NOTE: Your current PATH and PYTHONPATH environment variables are honored
      when launching via the wrapper script, while launching QGIS.app
      bundle they are not.

For standalone Python development, set the following environment variable:
  export PYTHONPATH=/usr/local/lib/qt-4/python2.7/site-packages:/usr/local/lib/python2.7/site-packages:$PYTHONPATH

Developer frameworks are installed in:
  /usr/local/opt/qgis2-ltr/lib/qgis-dev
  NOTE: not symlinked to HOMEBREW_PREFIX/Frameworks, which affects isolation.
        Use dyld -F option in CPPFLAGS/LDFLAGS when building other software.

If you have built GRASS 6.4.x or 7.0.x support for the Processing plugin set
the following in QGIS:
  Processing->Options: Providers->GRASS commands->GRASS folder to:
     /usr/local/opt/grass6/grass-base
  Processing->Options: Providers->GRASS GIS 7 commands->GRASS 7 folder to:
     /usr/local/opt/grass7/grass-base


This formula is keg-only, which means it was not symlinked into /usr/local,
because to allow for multiple QGIS installs.`


`Session info ---------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.1 (2017-06-30)
 system   x86_64, darwin15.6.0        
 ui       RStudio (1.0.143)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/Los_Angeles         
 date     2017-07-10                  

Packages -------------------------------------------------------------------------------------------------------
 package    * version date       source        
 base       * 3.4.1   2017-07-10 local         
 compiler     3.4.1   2017-07-10 local         
 datasets   * 3.4.1   2017-07-10 local         
 DBI          0.7     2017-06-18 CRAN (R 3.4.1)
 devtools     1.13.2  2017-06-02 CRAN (R 3.4.1)
 digest       0.6.12  2017-01-27 CRAN (R 3.4.1)
 graphics   * 3.4.1   2017-07-10 local         
 grDevices  * 3.4.1   2017-07-10 local         
 grid         3.4.1   2017-07-10 local         
 hms          0.3     2016-11-22 CRAN (R 3.4.1)
 lattice      0.20-35 2017-03-25 CRAN (R 3.4.1)
 magrittr     1.5     2014-11-22 CRAN (R 3.4.1)
 memoise      1.1.0   2017-04-21 CRAN (R 3.4.1)
 methods    * 3.4.1   2017-07-10 local         
 parallel     3.4.1   2017-07-10 local         
 R6           2.2.2   2017-06-17 CRAN (R 3.4.1)
 raster       2.5-8   2016-06-02 CRAN (R 3.4.1)
 Rcpp         0.12.11 2017-05-22 CRAN (R 3.4.1)
 readr        1.1.1   2017-05-16 CRAN (R 3.4.1)
 reticulate   0.9     2017-06-23 CRAN (R 3.4.1)
 rgdal        1.2-8   2017-07-01 CRAN (R 3.4.1)
 rlang        0.1.1   2017-05-18 CRAN (R 3.4.1)
 RQGIS      * 1.0.1   2017-06-27 CRAN (R 3.4.1)
 sf           0.5-1   2017-06-23 CRAN (R 3.4.1)
 sp           1.2-5   2017-06-29 CRAN (R 3.4.1)
 stats      * 3.4.1   2017-07-10 local         
 stringi      1.1.5   2017-04-07 CRAN (R 3.4.1)
 stringr      1.2.0   2017-02-18 CRAN (R 3.4.1)
 tibble       1.3.3   2017-05-28 CRAN (R 3.4.1)
 tools        3.4.1   2017-07-10 local         
 udunits2     0.13    2016-11-17 CRAN (R 3.4.1)
 units        0.4-5   2017-06-15 CRAN (R 3.4.1)
 utils      * 3.4.1   2017-07-10 local         
 withr        1.0.2   2016-06-20 CRAN (R 3.4.1)`

**Comment by luisspuerto** [comment] 2017-07-10 19:56
PS/ I've moved the QGIS.app from `/usr/local/opt/qgis2` to `/Applications`

**Comment by pat-s** [comment] 2017-07-10 20:06
Thanks. I cannot reproduce your error and it seems that it is a path issue on your side. Is your `qgis2` installation located at `/usr/local/Cellar/qgis2/2.18.10` or somewhere else? 

`/usr/local/opt/qgis2` is a symlink linking to `/usr/local/Cellar/qgis2/2.18.10`. Is that the same on your side? 

In any case, please try `brew reinstall qgis2` and do not change the default and see if that works. `brew install qgis2-ltr` is a lot faster because there is a bottle available (if you do not want to wait until the source installation has finished).

**Comment by luisspuerto** [comment] 2017-07-10 20:15
Seems that everything is correct here: 

```
 lpuerto@MBP-lpuerto  /  ls /usr/local/Cellar/qgis2/2.18.10
COPYING              NEWS                 fcgi-bin             share
ChangeLog            README.md            lib
INSTALL_RECEIPT.json bin                  libexec
 lpuerto@MBP-lpuerto  /  ls /usr/local/opt/qgis2
COPYING              NEWS                 fcgi-bin             share
ChangeLog            README.md            lib
INSTALL_RECEIPT.json bin                  libexec
 lpuerto@MBP-lpuerto  /  ls /usr/local/Cellar/qgis2/2.18.10
COPYING              NEWS                 fcgi-bin             share
ChangeLog            README.md            lib
INSTALL_RECEIPT.json bin                  libexec
```

Can I set the path manually somehow? I've already installed qgis2 and I haven't change anything. I just move the app to the application folder because it's really annoying not be able to find the app with spotlight.

**Comment by pat-s** [comment] 2017-07-10 20:20
Sure, you can do `set_env(root = "/usr/local/Cellar/qgis2/2.18.10/QGIS.app")`. That should work.

Nevertheless, it leaves me puzzled why this error occurs on your side. If you stumble upon a possible reason, let me know - I cannot reproduce it on my side.

**Comment by luisspuerto** [comment] 2017-07-10 20:58
ok! 

I found the solution... I guess that what you send me also works. The problem was that I moved the QGIS.app to /Applications. I just copy it back to it's original place and it works. 

I guess that if you install qgis with homebrew the package detects the Homebrew installation and then try to find the app there. Since it's not longer there, the problem arises. 

I've decided to set `set_env(root = "/Applications/QGIS.app")` and move every update of QGIS to /Application folder. What is your opinion about this? A warning appears saying that I'm using the Kyngchaos installation (I'm not) and that some problems and warnings can arise. Are those problems due to the location of the QGIS app or to the complication itself? 

I'm weary of have two qgis apps for the sake of space optimization and because I don't know if the configuration of one would be the same in the other one (Sorry I'm not an expert in the matter)

**Comment by luisspuerto** [comment] 2017-07-10 21:01
PS/ Summing up, do you think it's better to have just one apps in `/Applications` and point out to that installation, or should I leave the homebrew installation as it is and copy the app to `/Applications`

Thanks!

**Comment by luisspuerto** [comment] 2017-07-10 21:14
I just found that if move the QGIS.app from `/usr/local/Cellar/qgis2/2.18.10/QGIS.app` to `/Applications` and then I create a symbolic link from `/Applications/QGIS.app` to `/usr/local/Cellar/qgis2/2.18.10/` seems that everything works.

**Comment by luisspuerto** [comment] 2017-07-10 21:19
in terminal: `ln -s /Applications/QGIS.app /usr/local/Cellar/qgis2/2.18.10/QGIS.app`

One last question, why every time I input `qgis_session_info()` in rStudio another instance of rStudio try to fire up 
![screen shot 2017-07-10 at 14 19 07](https://user-images.githubusercontent.com/22882880/28040482-c7369af8-657a-11e7-8856-70dc3631e6ae.png)

**Comment by pat-s** [comment] 2017-07-10 21:42
> I found the solution... I guess that what you send me also works. The problem was that I moved the QGIS.app to /Applications. I just copy it back to it's original place and it works.

Ah yes, if you move it `RQGIS` does not find it in its original place - I initially thought you just copied it. Simply moving things around might also have other bad follow up effects as not only `RQGIS` might be unable to find the `.app`.  Its always better to copy and create a symlink. 

> I've decided to set set_env(root = "/Applications/QGIS.app") and move every update of QGIS to /Application folder. What is your opinion about this?

If you check `brew info qgis2` it states:

"You may also symlink QGIS.app into /Applications or ~/Applications:
  brew linkapps [--local]"

"To directly run the `QGIS.app/Contents/MacOS/QGIS` binary use the wrapper
script pre-defined with Homebrew prefix environment variables:
  /usr/local/opt/qgis2/bin/qgis2"

I would either write a custom bash script which opens `/usr/local/opt/qgis2/bin/qgis2` when you call `qgis2` from the command line or place the `.app` in the dock permanently. I do not want to do `brew linkapps` every time there is an update just to have it working with spotlight. 

However, there are many ways how to achieve this and you should just go with the one that suits you most. 

> A warning appears saying that I'm using the Kyngchaos installation (I'm not) and that some problems and warnings can arise. Are those problems due to the location of the QGIS app or to the complication itself?

That's due to the move of the `.app` to `/Applications`.  This is the usual way we detect/separate homebrew/Kyngchaos installations atm. Back then I was thinking that this could be a possible issue but so far nobody (besides you now) reported this problem. If more people will report this I might use a different logic to check for the different QGIS installation strategies. 

> One last question, why every time I input qgis_session_info() in rStudio another instance of rStudio try to fire up

That's `reticulate` working in the background sending the python calls to the QGIS API. Its no R/RStudio instance but actually a python process being displayed with a R logo because it was initially called from R. 

I close this issue as your issue is resolved. Happy `RQGIS`ing :)

**Closed by pat-s** 2017-07-10 21:42 UTC
Labels: help wanted, macOS
